version: '3.8'

services:
  staff:
    build:
      context: ../
      dockerfile: staff/Dockerfile
    command: gunicorn django_air.wsgi --bind 0.0.0.0:8000 --workers 4 --threads 4
    volumes:
      - ../staff:/apps/staff
      - static_volume:/apps/staff/static
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of the project
    env_file:
      - ../.env/.dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  staff_celery_worker:
    build:
      context: ../
      dockerfile: staff/Dockerfile
    command: celery -A django_air worker -l INFO
    volumes:
      - ../staff:/apps/staff
    env_file:
      - ../.env/.dev
    depends_on:
      - staff

  staff_celery_beat:
    build:
      context: ../
      dockerfile: staff/Dockerfile
    command: celery -A django_air beat -l INFO
    volumes:
      - ../staff:/apps/staff
    env_file:
      - ../.env/.dev
    depends_on:
      - staff

  staff_flower:
    build:
      context: ../
      dockerfile: staff/Dockerfile
    command: celery -A django_air --broker="${CELERY_BROKER}" flower --url-prefix=staff_flower
    volumes:
      - ../staff:/apps/staff
    env_file:
      - ../.env/.dev
    ports:
      - 5555:5555
    depends_on:
      - staff

  client:
    build:
      context: ../
      dockerfile: client/Dockerfile
    command: gunicorn django_air.wsgi --bind 0.0.0.0:8001 --workers 4 --threads 4
    volumes:
      - ../client:/apps/client
      - static_volume:/apps/client/static
    ports:
      - 8001:8001
    # env_file is used to manage the env variables of the project
    env_file:
      - ../.env/.dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  client_celery_worker:
    build:
      context: ../
      dockerfile: client/Dockerfile
    command: celery -A django_air worker -l INFO
    volumes:
      - ../client:/apps/client
    env_file:
      - ../.env/.dev
    depends_on:
      - client

  client_celery_beat:
    build:
      context: ../
      dockerfile: client/Dockerfile
    command: celery -A django_air beat -l INFO
    volumes:
      - ../client:/apps/client
    env_file:
      - ../.env/.dev
    depends_on:
      - client

  client_flower:
    build:
      context: ../
      dockerfile: client/Dockerfile
    command: celery -A django_air --broker="${CELERY_BROKER}" flower --url-prefix=client_flower --port=5556
    volumes:
      - ../client:/apps/client
    env_file:
      - ../.env/.dev
    ports:
      - 5556:5556
    depends_on:
      - client

volumes:
  postgres_data: {}
  static_volume: {}
