version: '3.8'

services:
  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/apps/static
    depends_on:
      - staff

  staff:
    build:
      context: ../
      dockerfile: staff/Dockerfile
    command: gunicorn django_air.wsgi --bind 0.0.0.0:8000 --workers 4 --threads 4
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - ../staff:/apps/staff
      - static_volume:/apps/staff/static
    expose:
      - 8000
    # env_file is used to manage the env variables of the project
    env_file:
      - ../.env/.dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  staff_celery_worker:
    build:
      context: ../
      dockerfile: staff/Dockerfile
    command: celery -A django_air worker -l INFO
    volumes:
      - ../staff:/apps/staff
    env_file:
      - ../.env/.dev
    depends_on:
      - staff

  staff_celery_beat:
    build:
      context: ../
      dockerfile: staff/Dockerfile
    command: celery -A django_air beat -l INFO
    volumes:
      - ../staff:/apps/staff
    env_file:
      - ../.env/.dev
    depends_on:
      - staff

  staff_flower:
    build:
      context: ../
      dockerfile: staff/Dockerfile
    command: celery -A django_air --broker="${CELERY_BROKER}" flower --url-prefix=staff_flower
    volumes:
      - ../staff:/apps/staff
    env_file:
      - ../.env/.dev
    expose:
      - 5555
    depends_on:
      - staff

  client:
    build:
      context: ../
      dockerfile: client/Dockerfile
    # '/start' is the shell script used to run the service
    command: gunicorn django_air.wsgi --bind 0.0.0.0:8001 --workers 4 --threads 4
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - ../client:/apps/client
      - static_volume:/apps/client/static
    expose:
      - 8001
    # env_file is used to manage the env variables of the project
    env_file:
      - ../.env/.dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  client_celery_worker:
    build:
      context: ../
      dockerfile: client/Dockerfile
    command: celery -A django_air worker -l INFO
    volumes:
      - ../client:/apps/client
    env_file:
      - ../.env/.dev
    depends_on:
      - client

  client_celery_beat:
    build:
      context: ../
      dockerfile: client/Dockerfile
    command: celery -A django_air beat -l INFO
    volumes:
      - ../client:/apps/client
    env_file:
      - ../.env/.dev
    depends_on:
      - client

  client_flower:
    build:
      context: ../
      dockerfile: client/Dockerfile
    command: celery -A django_air --broker="${CELERY_BROKER}" flower --url-prefix=client_flower --port=5556
    volumes:
      - ../client:/apps/client
    env_file:
      - ../.env/.dev
    expose:
      - 5556
    depends_on:
      - client

volumes:
  postgres_data: {}
  static_volume: {}
