server {
    listen 80;
    server_name _;
    server_tokens off;

    client_max_body_size 20M;

    location /staff {
        try_files $uri @staff;
    }

    location /staff/admin {
        try_files $uri @staff;
    }

    location @staff {
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://staff:8000;
    }

    location /staff_flower {
        proxy_pass http://staff_flower:5555;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri @client;
    }

    location /admin {
        try_files $uri @client;
    }

    location @client {
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://client:8001;
    }

    location /client_flower {
        proxy_pass http://client_flower:5556;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static/ {
        autoindex on;
        alias /apps/static/;
    }

}
